apiVersion: ipam.nddr.yndd.io/v1alpha1
kind: Register
metadata:
  name: alloc-loopback-leaf1
  namespace: default
spec:
  oda:  
  - key: organization
    value: nokia
  registry-name: nokia
  network-instance-name: default
  register:
    selector:
    - key: purpose
      value: loopback
    - key: address-family
      value: ipv4
    source-tag:
    - key: node
      value: leaf2