apiVersion: ipam.nddr.yndd.io/v1alpha1
kind: Register
metadata:
  name: alloc-link-isl1
  namespace: default
spec:
  oda:  
  - key: organization
    value: nokia
  registry-name: nokia
  network-instance-name: default
  register:
    selector:
    - key: purpose
      value: isl
    - key: address-family
      value: ipv4
    source-tag:
    - key: leaf1
      value: lag-50
    - key: leaf2
      value: lag-50