//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 NDD.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/yndd/nddo-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ipam) DeepCopyInto(out *Ipam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ipam.
func (in *Ipam) DeepCopy() *Ipam {
	if in == nil {
		return nil
	}
	out := new(Ipam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ipam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpam) DeepCopyInto(out *IpamIpam) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpam.
func (in *IpamIpam) DeepCopy() *IpamIpam {
	if in == nil {
		return nil
	}
	out := new(IpamIpam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamNetworkInstance) DeepCopyInto(out *IpamIpamNetworkInstance) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.AllocationStrategy != nil {
		in, out := &in.AllocationStrategy, &out.AllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.DefaultPrefixLength != nil {
		in, out := &in.DefaultPrefixLength, &out.DefaultPrefixLength
		*out = make(map[string]*IpamIpamNetworkInstanceDefaultPrefixLength, len(*in))
		for key, val := range *in {
			var outVal *IpamIpamNetworkInstanceDefaultPrefixLength
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(IpamIpamNetworkInstanceDefaultPrefixLength)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamNetworkInstance.
func (in *IpamIpamNetworkInstance) DeepCopy() *IpamIpamNetworkInstance {
	if in == nil {
		return nil
	}
	out := new(IpamIpamNetworkInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamNetworkInstanceDefaultPrefixLength) DeepCopyInto(out *IpamIpamNetworkInstanceDefaultPrefixLength) {
	*out = *in
	if in.AddressFamily != nil {
		in, out := &in.AddressFamily, &out.AddressFamily
		*out = make(map[string]*uint32, len(*in))
		for key, val := range *in {
			var outVal *uint32
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(uint32)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamNetworkInstanceDefaultPrefixLength.
func (in *IpamIpamNetworkInstanceDefaultPrefixLength) DeepCopy() *IpamIpamNetworkInstanceDefaultPrefixLength {
	if in == nil {
		return nil
	}
	out := new(IpamIpamNetworkInstanceDefaultPrefixLength)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamIpamNetworkInstanceIpPrefix) DeepCopyInto(out *IpamIpamNetworkInstanceIpPrefix) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(bool)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamIpamNetworkInstanceIpPrefix.
func (in *IpamIpamNetworkInstanceIpPrefix) DeepCopy() *IpamIpamNetworkInstanceIpPrefix {
	if in == nil {
		return nil
	}
	out := new(IpamIpamNetworkInstanceIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamList) DeepCopyInto(out *IpamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ipam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamList.
func (in *IpamList) DeepCopy() *IpamList {
	if in == nil {
		return nil
	}
	out := new(IpamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamNetworkInstance) DeepCopyInto(out *IpamNetworkInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamNetworkInstance.
func (in *IpamNetworkInstance) DeepCopy() *IpamNetworkInstance {
	if in == nil {
		return nil
	}
	out := new(IpamNetworkInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamNetworkInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamNetworkInstanceIpPrefix) DeepCopyInto(out *IpamNetworkInstanceIpPrefix) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamNetworkInstanceIpPrefix.
func (in *IpamNetworkInstanceIpPrefix) DeepCopy() *IpamNetworkInstanceIpPrefix {
	if in == nil {
		return nil
	}
	out := new(IpamNetworkInstanceIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamNetworkInstanceIpPrefix) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamNetworkInstanceIpPrefixList) DeepCopyInto(out *IpamNetworkInstanceIpPrefixList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamNetworkInstanceIpPrefix, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamNetworkInstanceIpPrefixList.
func (in *IpamNetworkInstanceIpPrefixList) DeepCopy() *IpamNetworkInstanceIpPrefixList {
	if in == nil {
		return nil
	}
	out := new(IpamNetworkInstanceIpPrefixList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamNetworkInstanceIpPrefixList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamNetworkInstanceIpPrefixSpec) DeepCopyInto(out *IpamNetworkInstanceIpPrefixSpec) {
	*out = *in
	if in.IpamNetworkInstanceIpPrefix != nil {
		in, out := &in.IpamNetworkInstanceIpPrefix, &out.IpamNetworkInstanceIpPrefix
		*out = new(IpamIpamNetworkInstanceIpPrefix)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamNetworkInstanceIpPrefixSpec.
func (in *IpamNetworkInstanceIpPrefixSpec) DeepCopy() *IpamNetworkInstanceIpPrefixSpec {
	if in == nil {
		return nil
	}
	out := new(IpamNetworkInstanceIpPrefixSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamNetworkInstanceIpPrefixStatus) DeepCopyInto(out *IpamNetworkInstanceIpPrefixStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.IpamName != nil {
		in, out := &in.IpamName, &out.IpamName
		*out = new(string)
		**out = **in
	}
	if in.OrganizationName != nil {
		in, out := &in.OrganizationName, &out.OrganizationName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentName != nil {
		in, out := &in.DeploymentName, &out.DeploymentName
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstanceName != nil {
		in, out := &in.NetworkInstanceName, &out.NetworkInstanceName
		*out = new(string)
		**out = **in
	}
	if in.IpPrefixName != nil {
		in, out := &in.IpPrefixName, &out.IpPrefixName
		*out = new(string)
		**out = **in
	}
	if in.IpamNetworkInstanceIpPrefix != nil {
		in, out := &in.IpamNetworkInstanceIpPrefix, &out.IpamNetworkInstanceIpPrefix
		*out = new(NddrIpamIpamNetworkInstanceIpPrefix)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamNetworkInstanceIpPrefixStatus.
func (in *IpamNetworkInstanceIpPrefixStatus) DeepCopy() *IpamNetworkInstanceIpPrefixStatus {
	if in == nil {
		return nil
	}
	out := new(IpamNetworkInstanceIpPrefixStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamNetworkInstanceList) DeepCopyInto(out *IpamNetworkInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IpamNetworkInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamNetworkInstanceList.
func (in *IpamNetworkInstanceList) DeepCopy() *IpamNetworkInstanceList {
	if in == nil {
		return nil
	}
	out := new(IpamNetworkInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IpamNetworkInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamNetworkInstanceSpec) DeepCopyInto(out *IpamNetworkInstanceSpec) {
	*out = *in
	if in.IpamNetworkInstance != nil {
		in, out := &in.IpamNetworkInstance, &out.IpamNetworkInstance
		*out = new(IpamIpamNetworkInstance)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamNetworkInstanceSpec.
func (in *IpamNetworkInstanceSpec) DeepCopy() *IpamNetworkInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(IpamNetworkInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamNetworkInstanceStatus) DeepCopyInto(out *IpamNetworkInstanceStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.OrganizationName != nil {
		in, out := &in.OrganizationName, &out.OrganizationName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentName != nil {
		in, out := &in.DeploymentName, &out.DeploymentName
		*out = new(string)
		**out = **in
	}
	if in.IpamName != nil {
		in, out := &in.IpamName, &out.IpamName
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstanceName != nil {
		in, out := &in.NetworkInstanceName, &out.NetworkInstanceName
		*out = new(string)
		**out = **in
	}
	if in.IpamNetworkInstance != nil {
		in, out := &in.IpamNetworkInstance, &out.IpamNetworkInstance
		*out = new(NddrIpamIpamNetworkInstance)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamNetworkInstanceStatus.
func (in *IpamNetworkInstanceStatus) DeepCopy() *IpamNetworkInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(IpamNetworkInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamRegister) DeepCopyInto(out *IpamRegister) {
	*out = *in
	if in.AddressFamily != nil {
		in, out := &in.AddressFamily, &out.AddressFamily
		*out = new(string)
		**out = **in
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = new(string)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.SourceTag != nil {
		in, out := &in.SourceTag, &out.SourceTag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamRegister.
func (in *IpamRegister) DeepCopy() *IpamRegister {
	if in == nil {
		return nil
	}
	out := new(IpamRegister)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamSpec) DeepCopyInto(out *IpamSpec) {
	*out = *in
	if in.Ipam != nil {
		in, out := &in.Ipam, &out.Ipam
		*out = new(IpamIpam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamSpec.
func (in *IpamSpec) DeepCopy() *IpamSpec {
	if in == nil {
		return nil
	}
	out := new(IpamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IpamStatus) DeepCopyInto(out *IpamStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.OrganizationName != nil {
		in, out := &in.OrganizationName, &out.OrganizationName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentName != nil {
		in, out := &in.DeploymentName, &out.DeploymentName
		*out = new(string)
		**out = **in
	}
	if in.IpamName != nil {
		in, out := &in.IpamName, &out.IpamName
		*out = new(string)
		**out = **in
	}
	if in.Ipam != nil {
		in, out := &in.Ipam, &out.Ipam
		*out = new(NddrIpamIpam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IpamStatus.
func (in *IpamStatus) DeepCopy() *IpamStatus {
	if in == nil {
		return nil
	}
	out := new(IpamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpam) DeepCopyInto(out *NddrIpam) {
	*out = *in
	if in.Ipam != nil {
		in, out := &in.Ipam, &out.Ipam
		*out = new(NddrIpamIpam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpam.
func (in *NddrIpam) DeepCopy() *NddrIpam {
	if in == nil {
		return nil
	}
	out := new(NddrIpam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpam) DeepCopyInto(out *NddrIpamIpam) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.TenantName != nil {
		in, out := &in.TenantName, &out.TenantName
		*out = new(string)
		**out = **in
	}
	if in.VpcName != nil {
		in, out := &in.VpcName, &out.VpcName
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = make([]*NddrIpamIpamNetworkInstance, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddrIpamIpamNetworkInstance)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(NddrIpamIpamState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpam.
func (in *NddrIpamIpam) DeepCopy() *NddrIpamIpam {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstance) DeepCopyInto(out *NddrIpamIpamNetworkInstance) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.AllocationStrategy != nil {
		in, out := &in.AllocationStrategy, &out.AllocationStrategy
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.IpAddress != nil {
		in, out := &in.IpAddress, &out.IpAddress
		*out = make([]*NddrIpamIpamNetworkInstanceIpAddress, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddrIpamIpamNetworkInstanceIpAddress)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddrIpamIpamNetworkInstanceIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddrIpamIpamNetworkInstanceIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpRange != nil {
		in, out := &in.IpRange, &out.IpRange
		*out = make([]*NddrIpamIpamNetworkInstanceIpRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddrIpamIpamNetworkInstanceIpRange)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(NddrIpamIpamNetworkInstanceState)
		(*in).DeepCopyInto(*out)
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstance.
func (in *NddrIpamIpamNetworkInstance) DeepCopy() *NddrIpamIpamNetworkInstance {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpAddress) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpAddress) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DnsName != nil {
		in, out := &in.DnsName, &out.DnsName
		*out = new(string)
		**out = **in
	}
	if in.NatInside != nil {
		in, out := &in.NatInside, &out.NatInside
		*out = new(string)
		**out = **in
	}
	if in.NatOutside != nil {
		in, out := &in.NatOutside, &out.NatOutside
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(NddrIpamIpamNetworkInstanceIpAddressState)
		(*in).DeepCopyInto(*out)
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpAddress.
func (in *NddrIpamIpamNetworkInstanceIpAddress) DeepCopy() *NddrIpamIpamNetworkInstanceIpAddress {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpAddressState) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpAddressState) {
	*out = *in
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddrIpamIpamNetworkInstanceIpAddressStateIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddrIpamIpamNetworkInstanceIpAddressStateIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.IpRange != nil {
		in, out := &in.IpRange, &out.IpRange
		*out = make([]*NddrIpamIpamNetworkInstanceIpAddressStateIpRange, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddrIpamIpamNetworkInstanceIpAddressStateIpRange)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpAddressState.
func (in *NddrIpamIpamNetworkInstanceIpAddressState) DeepCopy() *NddrIpamIpamNetworkInstanceIpAddressState {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpAddressState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpAddressStateIpPrefix) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpAddressStateIpPrefix) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpAddressStateIpPrefix.
func (in *NddrIpamIpamNetworkInstanceIpAddressStateIpPrefix) DeepCopy() *NddrIpamIpamNetworkInstanceIpAddressStateIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpAddressStateIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpAddressStateIpRange) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpAddressStateIpRange) {
	*out = *in
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpAddressStateIpRange.
func (in *NddrIpamIpamNetworkInstanceIpAddressStateIpRange) DeepCopy() *NddrIpamIpamNetworkInstanceIpAddressStateIpRange {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpAddressStateIpRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpPrefix) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpPrefix) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Pool != nil {
		in, out := &in.Pool, &out.Pool
		*out = new(bool)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(NddrIpamIpamNetworkInstanceIpPrefixState)
		(*in).DeepCopyInto(*out)
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpPrefix.
func (in *NddrIpamIpamNetworkInstanceIpPrefix) DeepCopy() *NddrIpamIpamNetworkInstanceIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpPrefixState) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpPrefixState) {
	*out = *in
	if in.Adresses != nil {
		in, out := &in.Adresses, &out.Adresses
		*out = new(uint32)
		**out = **in
	}
	if in.Child != nil {
		in, out := &in.Child, &out.Child
		*out = new(NddrIpamIpamNetworkInstanceIpPrefixStateChild)
		(*in).DeepCopyInto(*out)
	}
	if in.Parent != nil {
		in, out := &in.Parent, &out.Parent
		*out = new(NddrIpamIpamNetworkInstanceIpPrefixStateParent)
		(*in).DeepCopyInto(*out)
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpPrefixState.
func (in *NddrIpamIpamNetworkInstanceIpPrefixState) DeepCopy() *NddrIpamIpamNetworkInstanceIpPrefixState {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpPrefixState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpPrefixStateChild) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpPrefixStateChild) {
	*out = *in
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddrIpamIpamNetworkInstanceIpPrefixStateChildIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddrIpamIpamNetworkInstanceIpPrefixStateChildIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpPrefixStateChild.
func (in *NddrIpamIpamNetworkInstanceIpPrefixStateChild) DeepCopy() *NddrIpamIpamNetworkInstanceIpPrefixStateChild {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpPrefixStateChild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpPrefixStateChildIpPrefix) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpPrefixStateChildIpPrefix) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpPrefixStateChildIpPrefix.
func (in *NddrIpamIpamNetworkInstanceIpPrefixStateChildIpPrefix) DeepCopy() *NddrIpamIpamNetworkInstanceIpPrefixStateChildIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpPrefixStateChildIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpPrefixStateParent) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpPrefixStateParent) {
	*out = *in
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddrIpamIpamNetworkInstanceIpPrefixStateParentIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddrIpamIpamNetworkInstanceIpPrefixStateParentIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpPrefixStateParent.
func (in *NddrIpamIpamNetworkInstanceIpPrefixStateParent) DeepCopy() *NddrIpamIpamNetworkInstanceIpPrefixStateParent {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpPrefixStateParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpPrefixStateParentIpPrefix) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpPrefixStateParentIpPrefix) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpPrefixStateParentIpPrefix.
func (in *NddrIpamIpamNetworkInstanceIpPrefixStateParentIpPrefix) DeepCopy() *NddrIpamIpamNetworkInstanceIpPrefixStateParentIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpPrefixStateParentIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpRange) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpRange) {
	*out = *in
	if in.AdminState != nil {
		in, out := &in.AdminState, &out.AdminState
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(NddrIpamIpamNetworkInstanceIpRangeState)
		(*in).DeepCopyInto(*out)
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpRange.
func (in *NddrIpamIpamNetworkInstanceIpRange) DeepCopy() *NddrIpamIpamNetworkInstanceIpRange {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpRangeState) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpRangeState) {
	*out = *in
	if in.Parent != nil {
		in, out := &in.Parent, &out.Parent
		*out = new(NddrIpamIpamNetworkInstanceIpRangeStateParent)
		(*in).DeepCopyInto(*out)
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(uint32)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpRangeState.
func (in *NddrIpamIpamNetworkInstanceIpRangeState) DeepCopy() *NddrIpamIpamNetworkInstanceIpRangeState {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpRangeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpRangeStateParent) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpRangeStateParent) {
	*out = *in
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = make([]*NddrIpamIpamNetworkInstanceIpRangeStateParentIpPrefix, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NddrIpamIpamNetworkInstanceIpRangeStateParentIpPrefix)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpRangeStateParent.
func (in *NddrIpamIpamNetworkInstanceIpRangeStateParent) DeepCopy() *NddrIpamIpamNetworkInstanceIpRangeStateParent {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpRangeStateParent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceIpRangeStateParentIpPrefix) DeepCopyInto(out *NddrIpamIpamNetworkInstanceIpRangeStateParentIpPrefix) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceIpRangeStateParentIpPrefix.
func (in *NddrIpamIpamNetworkInstanceIpRangeStateParentIpPrefix) DeepCopy() *NddrIpamIpamNetworkInstanceIpRangeStateParentIpPrefix {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceIpRangeStateParentIpPrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamNetworkInstanceState) DeepCopyInto(out *NddrIpamIpamNetworkInstanceState) {
	*out = *in
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamNetworkInstanceState.
func (in *NddrIpamIpamNetworkInstanceState) DeepCopy() *NddrIpamIpamNetworkInstanceState {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamNetworkInstanceState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamIpamState) DeepCopyInto(out *NddrIpamIpamState) {
	*out = *in
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]*v1.Tag, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(v1.Tag)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamIpamState.
func (in *NddrIpamIpamState) DeepCopy() *NddrIpamIpamState {
	if in == nil {
		return nil
	}
	out := new(NddrIpamIpamState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrIpamRegister) DeepCopyInto(out *NddrIpamRegister) {
	*out = *in
	in.IpamRegister.DeepCopyInto(&out.IpamRegister)
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(NddrRegisterState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrIpamRegister.
func (in *NddrIpamRegister) DeepCopy() *NddrIpamRegister {
	if in == nil {
		return nil
	}
	out := new(NddrIpamRegister)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddrRegisterState) DeepCopyInto(out *NddrRegisterState) {
	*out = *in
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddrRegisterState.
func (in *NddrRegisterState) DeepCopy() *NddrRegisterState {
	if in == nil {
		return nil
	}
	out := new(NddrRegisterState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Register) DeepCopyInto(out *Register) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Register.
func (in *Register) DeepCopy() *Register {
	if in == nil {
		return nil
	}
	out := new(Register)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Register) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegisterList) DeepCopyInto(out *RegisterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Register, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegisterList.
func (in *RegisterList) DeepCopy() *RegisterList {
	if in == nil {
		return nil
	}
	out := new(RegisterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegisterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegisterSpec) DeepCopyInto(out *RegisterSpec) {
	*out = *in
	if in.Register != nil {
		in, out := &in.Register, &out.Register
		*out = new(IpamRegister)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegisterSpec.
func (in *RegisterSpec) DeepCopy() *RegisterSpec {
	if in == nil {
		return nil
	}
	out := new(RegisterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegisterStatus) DeepCopyInto(out *RegisterStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
	if in.OrganizationName != nil {
		in, out := &in.OrganizationName, &out.OrganizationName
		*out = new(string)
		**out = **in
	}
	if in.DeploymentName != nil {
		in, out := &in.DeploymentName, &out.DeploymentName
		*out = new(string)
		**out = **in
	}
	if in.IpamName != nil {
		in, out := &in.IpamName, &out.IpamName
		*out = new(string)
		**out = **in
	}
	if in.NetworkInstanceName != nil {
		in, out := &in.NetworkInstanceName, &out.NetworkInstanceName
		*out = new(string)
		**out = **in
	}
	if in.Register != nil {
		in, out := &in.Register, &out.Register
		*out = new(NddrIpamRegister)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegisterStatus.
func (in *RegisterStatus) DeepCopy() *RegisterStatus {
	if in == nil {
		return nil
	}
	out := new(RegisterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Root) DeepCopyInto(out *Root) {
	*out = *in
	if in.IpamNddrIpam != nil {
		in, out := &in.IpamNddrIpam, &out.IpamNddrIpam
		*out = new(NddrIpam)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Root.
func (in *Root) DeepCopy() *Root {
	if in == nil {
		return nil
	}
	out := new(Root)
	in.DeepCopyInto(out)
	return out
}
